### ISSUE TITLE
Cannot stop server after disconnecting nc client

### ISSUE THREAD

**Issue by LegendreMatisse** [cbouwen/ft_irc#22]
When you open a server and you connect to it using "nc", you cannot stop the server after disconnecting the "nc" client.

Commands to reproduce:
-- Terminal 1
- ./ircserver 4884 matisse

-- Terminal 2
- nc 127.0.0.1 4884
- ctrl-c

-- Terminal 1
- "Client disconnected"
- ctrl-c ==> unresponsive

**Comment by cbouwen** [comment]
Client is waiting for USER RECEIVED to be set to true. We are going to overhaul the connection to make it compatible with nc
