### ISSUE TITLE
When multiple users of with the same name join the same channel, no messages are printed to the other client

### ISSUE THREAD

**Issue by LegendreMatisse** [cbouwen/ft_irc#37]

**Comment by cbouwen** [comment]
There should be unique usernames now which would make the overlap impossible.
The only thing I can think of if we join with irssi where nick gets set automatically.
I fixed this in the setnickname function though so maybe we can just call on this function instead of hardcoding it here?

**Comment by cbouwen** [comment]
Fixed with unique usernames
