### ISSUE TITLE
Seg fault when kicking a person in nc

### ISSUE THREAD

**Issue by LegendreMatisse** [cbouwen/ft_irc#61]
When 2 users are in the same channel in nc, there is a seg fault when 1 users tries to kick the other.

KICK tom ==> segfault

**Comment by LegendreMatisse** [comment]
Haven't tested it with irssi yet

**Comment by cbouwen** [comment]
This issue is because the command is wrongly passed. Kicking works. Parsing an incorrect command doesn't
