### ISSUE TITLE
NC - segfault when sending a PRIVMSG to a channel with an incomplete channelname

### ISSUE THREAD

**Issue by LegendreMatisse** [cbouwen/ft_irc#63]
When you want to send a message to a channel, but don't give the correct channel name, there is a segfault.

Command: PRIVMSG #gen (the correct channel name is general)

This issue exists in NC, haven't tested irssi yet.

**Comment by LegendreMatisse** [comment]
I think you can expand this issue to every command. Incomplete or non existent channel names cause a segfault.

**Comment by cbouwen** [comment]
Issue where command is incorrectly parsed. Not because PRIVSMSG is broken.
