### ISSUE TITLE
NC - segfault when sending a message to a channel without using the #

### ISSUE THREAD

**Issue by LegendreMatisse** [cbouwen/ft_irc#64]
There is a segfault when sending a message to a channel in NC without using the # in front of the channel.

Command: PRIVMSG general test

**Comment by cbouwen** [comment]
This issue pertains to parsing. 
1: Let's make sure that every channel that gets created starts with a #. If it does not, do not accept it.
2: More error checks during parsing. Check if channelname is correct and amount of arguments.
