### ISSUE TITLE
NC messages are sent to new clients when a client is killed unexpectedly

### ISSUE THREAD

**Issue by LegendreMatisse** [cbouwen/ft_irc#71]
When you kill an NC client unexpectedly while messages are being sent to it there is some undefined behavior.

If you try to connect a new NC client to the server, the messages that are being sent to the server end up in the new client. Regardless if the client has a user and if that user is connected to channel the messages are being sent to

**Comment by cbouwen** [comment]
I can't recreate this. Need Matisse for this

**Comment by cbouwen** [comment]
Users weren't correctly cut from clients. Fixed now
