### ISSUE TITLE
NC inviting a user using irssi doesn't work

### ISSUE THREAD

**Issue by LegendreMatisse** [cbouwen/ft_irc#72]
I might also be using the wron command for this one.

`/invite #general bb`

If you invite a user in nc using the irssi client, the invite doesn't work. The inverse does work, I can invite an irssi user using nc without any issue.

**Comment by cbouwen** [comment]
Irssi parses the '#' automatically so in this case the channel name would be ##general instead of #general.
The correct command is /invite general bb
