### ISSUE TITLE
NC strange behavior when you kill a client and are sending messages to the server

### ISSUE THREAD

**Issue by LegendreMatisse** [cbouwen/ft_irc#73]
If you kill an nc client with an unfinished command just sent to the server there is strange behaviour. Any nc message you send to the server get the "error while sending message to the client" error. It's difficult to explain, so I
![image](https://github.com/user-attachments/assets/f07bd277-da15-4faa-b884-9423754e03e8)
 added a screenshot below.

**Comment by cbouwen** [comment]
I can't recreate this. Need Matisse for this
