### ISSUE TITLE
IRSSI trying to join a channel with password bricks the client

### ISSUE THREAD

**Issue by LegendreMatisse** [cbouwen/ft_irc#78]
If you try to join a channel in irssi with password protection (password set in nc), the client breaks.

I first tried to join the channel without entering a password, and then tried to join the channel with a password, but this bricked the client. No seg fault, the client was just unresponsive.

**Comment by cbouwen** [comment]
Again, this seems to be an issue in how irssi is handling the joining of channels. Most of the current issues all boil down to this. Will close this comment to have a better overview of the problems
