### ISSUE TITLE
Makefile incorrect 

### ISSUE THREAD

**Issue by cbouwen** [cbouwen/ft_irc#87]
Makefile does not correctly compile. Somehow it uses g++ to create the object files even though it is nowhere mentioned. All of the flags aren't used either. If I try and compile directly (without creating object files) I get a lot of compilation errors. 

Can you guys look into this? Makefiles aren't my forte. If you can just get it to try and compile but with compilation errors, I can fix the compilation errors.

Thanks

**Comment by yannickdoteu** [comment]
fixed this in branch fix-makefile, didn't push to master because it gives new compilation errors
